<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="C100-189s-iMac.local" ignored="0" name="Error Validations" tests="7" failures="1" timestamp="2022-10-20T10:06:21 IST" time="55.882" errors="0">
  <testcase name="loginError" time="0.641" classname="newmaven.Tests.errorMessageValidations">
    <skipped/>
  </testcase> <!-- loginError -->
  <testcase name="loginError" time="0.703" classname="newmaven.Tests.errorMessageValidations">
    <skipped/>
  </testcase> <!-- loginError -->
  <testcase name="loginError" time="0.79" classname="newmaven.Tests.errorMessageValidations">
    <skipped/>
  </testcase> <!-- loginError -->
  <testcase name="loginError" time="0.656" classname="newmaven.Tests.errorMessageValidations">
    <skipped/>
  </testcase> <!-- loginError -->
  <testcase name="loginError" time="0.718" classname="newmaven.Tests.errorMessageValidations">
    <skipped/>
  </testcase> <!-- loginError -->
  <testcase name="loginError" time="0.672" classname="newmaven.Tests.errorMessageValidations">
    <failure type="java.lang.AssertionError" message="expected:&amp;lt;Incorrect email password.&amp;gt; but was:&amp;lt;Incorrect email or password.&amp;gt;">
      <![CDATA[java.lang.AssertionError: expected:<Incorrect email password.> but was:<Incorrect email or password.>
at newmaven.Tests.errorMessageValidations.loginError(errorMessageValidations.java:43)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:750)
... Removed 14 stack frames]]>
    </failure>
  </testcase> <!-- loginError -->
  <testcase name="productMatchValidation" time="2.559" classname="newmaven.Tests.errorMessageValidations"/>
</testsuite> <!-- Error Validations -->
